[platformio]
default_envs = esp32
description = "CEREBRO ESP32 - FSM + Sensores + I2C Maestro"

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    Wire
    bblanchon/ArduinoJson@^7.0.4  ; para serialización (opcional)
build_flags = 
    -D FSM_DEBUG
